### ISSUE TITLE
Modify selected image list 

### ISSUE THREAD

**Issue by stefanocarna** [readbeard/ImageSqueezer#12] opened 2020-12-03 16:47 UTC
Once some images are selected from the picker and added to the image selection, it is not possible to add other images to the list by repeating the process.
The button "add images" should be always available and should provide an additive result (add the images to the previous list rather than create a new list with the last selected images)

**Comment by readbeard** [comment] 2020-12-05 09:58
closing this issue as it's a duplicate of #6

**Closed as completed by readbeard** 2020-12-05 09:58 UTC
